# -*- coding: utf-8 -*- 
Import('LIB_TYPE')
Import('Target_env')
Import('Test_env')
Import('TARGET_LIB_FILE')
Import('TARGET_EXE_FILE')
Import('LIBSRC_FILES')
Import('SRC_FILES')
Import('TARGET_NAME')
Import('LIBS')
Import('SWUT_FILES')
Import('SWIT_FILES')

Target_env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME']=1

LIBSRC_FILES=LIBSRC_FILES+[
 '/home/t0/00_work/27_mobs/bench/direct_linking_ex/MainPrj_Repo/Module_B/out/x64_Linux_ubuntu/libsrc/libmodule.o',
 '/home/t0/00_work/27_mobs/bench/direct_linking_ex/MainPrj_Repo/Module_B/out/x64_Linux_ubuntu/libsrc/Module_B_imp.o',
]
print("\033[1;33m :x: chk "+str(LIBSRC_FILES)+"\033[m\n");

if (LIB_TYPE == 'Shared') :
    LIB_BUILDER=Target_env.SharedLibrary(TARGET_LIB_FILE,source=LIBSRC_FILES)
    print("\033[1;32m :x: chk "+str(Target_env)+"\033[m\n");
elif(LIB_TYPE == 'Static') :
    LIB_BUILDER=Target_env.StaticLibrary(TARGET_LIB_FILE,source=LIBSRC_FILES)

EXE_BUILDER=Target_env.Program(TARGET_EXE_FILE,SRC_FILES,LIBS=[TARGET_NAME]+LIBS)

if (SWUT_FILES != [] and SWIT_FILES != [] ):
    SWUT_BUILDER=Test_env.Program(TARGET_EXE_FILE+'_swut',SWUT_FILES)
    SWIT_BUILDER=Test_env.Program(TARGET_EXE_FILE+'_swit',SWIT_FILES)
    Depends( SWUT_BUILDER,TARGET_LIB_FILE)
    Depends( SWIT_BUILDER,TARGET_LIB_FILE)

Depends( EXE_BUILDER,TARGET_LIB_FILE)
